apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 00-kustomized-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: 8088f4c
    path: plugins/kustomized-helm
    plugin:
      name: kustomized-helm 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

