apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: haaska
resources:
  - certificate.yaml
  - home-assistant.yaml
  - ingress.yaml
  - namespace.yaml
  - service.yaml
  - smarthome.yaml
  - wwwroot.yaml