apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-proxy
  labels:
    app: smart-proxy
spec:
  revisionHistoryLimit: 3
  replicas: 2
  selector:
    matchLabels:
      app: smart-proxy
  template:
    metadata:
      labels:
        app: smart-proxy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - unraid-k8s
      containers:
        - name: smart-proxy
          image: saucelabs/forwarder
          ports:
            - containerPort: 3128
            - containerPort: 10000
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
            requests:
              memory: 128Mi
              cpu: 10m
          env:
            - name: FORWARDER_ADDRESS
              value: ":3128"
            - name: FORWARDER_PAC
              value: "http://wpad.http-proxy.kube/wpad.dat"
            - name: FORWARDER_LOG_HTTP
              value: "short-url" 
            - name: FORWARDER_API_ADDRESS
              value: ":10000" 
            - name: FORWARDER_LOG_LEVEL
              value: "info" 

          livenessProbe:
            exec:
              command:
                - forwarder
                - ready
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2
          readinessProbe:
            exec:
              command:
                - forwarder
                - ready
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2
          startupProbe:
            exec:
              command:
                - forwarder
                - ready
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2
---
kind: Service
apiVersion: v1
metadata:
  name: smart-proxy
spec:
  ipFamilies:
   - IPv6
   - IPv4
  ports:
    - protocol: TCP
      port: 3128
      targetPort: 3128
      name: smart-proxy
    - protocol: TCP
      port: 80
      targetPort: 10000
      name: admin
  selector:
    app: smart-proxy
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  externalTrafficPolicy: Cluster
