kind: Service
apiVersion: v1
metadata:
  name: uk-proxy
spec:
  ipFamilies:
   - IPv4
  ports:
    - protocol: TCP
      port: 3128
      targetPort: 3128
      name: http
    - protocol: TCP
      port: 1080
      targetPort: 3128
      name: http-2
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: azure
  selector:
    app: uk-proxy
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  externalTrafficPolicy: Cluster
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: uk-proxy
spec:
  revisionHistoryLimit: 3
  replicas: 2
  selector:
    matchLabels:
      app: uk-proxy
  template:
    metadata:
      # annotations:
      #   cni.projectcalico.org/ipv6pools: '["public-ipv6-pool"]'
      labels:
        app: uk-proxy
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
#          requiredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: uk-proxy
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - fake
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: uk-proxy
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: proxy
        securityContext:
          allowPrivilegeEscalation: false
        env:
          - name: SERVER_ADDR
            value: http://localhost:8080/
          - name: PROXY_PORT
            value: "3128"
          # 16 MB Send/Recv Window (Bandwidth latency product) 
          # should allow for 128Mb/s with a latency of 1 second
          - name: QUIC_SEND_WINDOW
            value: "16777216"
          - name: QUIC_RECV_WINDOW
            value: "16777216"

          # Force IPv4
          # - name: BIND_ADDR
          #   value: "[::]:0"
        #image: ghcr.io/arontsang/socat-curl-proxy:latest
        image: ghcr.io/arontsang/iroh-vpn-proxy/client:idle-timeout
        imagePullPolicy: Always
        ports:
        - containerPort: 3128
      - name: caddy
        image: caddy:2-alpine
        ports:
        - containerPort: 8080
        command: ["sh", "-c"]
        args:
          - |
            cat <<EOF | caddy run --adapter caddyfile --config -
            :8080 {
                reverse_proxy https://d9a3efd2b48745ea8180dafb6f9deda7.nicegrass-a1e7b9c1.uksouth.azurecontainerapps.io {
                    header_up Host {upstream_hostport}
                    
                    # Reads the token file from disk dynamically on every HTTP request
                    header_up Authorization "Bearer {file./var/run/secrets/tokens/azure-token}"
                }
            }
            EOF
        volumeMounts:
        # Mount the projected token volume into the Caddy container
        - name: azure-token
          mountPath: /var/run/secrets/tokens/azure-token
          readOnly: true
          subPath: k8s-auth-token
      volumes:
        - name: azure-token
          projected:
            sources:
              - serviceAccountToken:
                  audience: "api://azure"
                  expiration: 3600
                  path: k8s-auth-token
