apiVersion: apps/v1
kind: Deployment
metadata:
  name: wpad
  labels:
    app: wpad
spec:
  revisionHistoryLimit: 3
  replicas: 2
  selector:
    matchLabels:
      app: wpad
  template:
    metadata:
      labels:
        app: wpad
    spec:
      containers:
        - name: wpad
          image: public.ecr.aws/nginx/nginx:alpine-slim
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/wpad.dat
              name: script
              subPath: wpad.js
          resources:
            limits:
              memory: 8Mi
              cpu: 100m
            requests:
              memory: 8Mi
              cpu: 10m
          livenessProbe:
            httpGet:
              path: /wpad.dat
              port: 80
      volumes:
       - name: script
         configMap:
           name: script
---
kind: Service
apiVersion: v1
metadata:
  name: wpad
spec:
  ipFamilies:
   - IPv6
   - IPv4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    app: wpad
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  externalTrafficPolicy: Cluster
---