apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.16.1
          args:
            - --source=crd
            - --domain-filter=arontsang.com
            - --provider=cloudflare
            - '--txt-owner-id=aks-itools-iprd-ue'
            - --cloudflare-dns-records-per-page=5000
            - --managed-record-types=CNAME
            - --managed-record-types=A
          env:
            - name: CF_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-api-token-secret
                  key: api-token