apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-kv-cluster-store
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      vaultUrl: "https://kube-secrets.vault.azure.net/"
      identityId: "bd9dcb96-da6a-4c7d-ba19-e9fe28667eaf"
      tenantId: "4d0ec782-1b23-4888-ba2b-a2a62eba6abc"

---
apiVersion: external-secrets.io/v1  # <-- Update this too
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv-cluster-store
    kind: ClusterSecretStore
  target:
    name: test-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: foobar